[2025-01-27T10:06:17.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T10:06:17.937+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9843500346_2025-01-27T10-05-11-797136Z.find_reason_for_unanswered scheduled__2025-01-27T10:05:11.797136+00:00 [queued]>
[2025-01-27T10:06:17.941+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9843500346_2025-01-27T10-05-11-797136Z.find_reason_for_unanswered scheduled__2025-01-27T10:05:11.797136+00:00 [queued]>
[2025-01-27T10:06:17.941+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-27T10:06:17.947+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): find_reason_for_unanswered> on 2025-01-27 10:05:11.797136+00:00
[2025-01-27T10:06:17.952+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4869) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-27T10:06:17.952+0000] {standard_task_runner.py:72} INFO - Started process 4871 to run task
[2025-01-27T10:06:17.953+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9843500346_2025-01-27T10-05-11-797136Z', 'find_reason_for_unanswered', 'scheduled__2025-01-27T10:05:11.797136+00:00', '--job-id', '1366', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpvz8qt28k']
[2025-01-27T10:06:17.953+0000] {standard_task_runner.py:105} INFO - Job 1366: Subtask find_reason_for_unanswered
[2025-01-27T10:06:17.974+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9843500346_2025-01-27T10-05-11-797136Z.find_reason_for_unanswered scheduled__2025-01-27T10:05:11.797136+00:00 [running]> on host 680cb867086b
[2025-01-27T10:06:18.008+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9843500346_2025-01-27T10-05-11-797136Z' AIRFLOW_CTX_TASK_ID='find_reason_for_unanswered' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T10:05:11.797136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T10:05:11.797136+00:00'
[2025-01-27T10:06:18.009+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T10:06:18.010+0000] {logging_mixin.py:190} INFO - demo-scheduled-from-ui-worldlinkfbed7fae-181a-4195-85cb-045bcee6c18d
[2025-01-27T10:06:18.010+0000] {logging_mixin.py:190} INFO - cause_txt: switch_off
[2025-01-27T10:06:18.014+0000] {base.py:84} INFO - Retrieving connection 'aicallagent'
[2025-01-27T10:06:18.017+0000] {sql.py:544} INFO - Running statement: UPDATE user_details SET status = 'switch_off', modified_on_utc = now() at time zone 'utc' WHERE caller_id = 'demo-scheduled-from-ui-worldlinkfbed7fae-181a-4195-85cb-045bcee6c18d', parameters: None
[2025-01-27T10:06:18.019+0000] {sql.py:553} INFO - Rows affected: 1
[2025-01-27T10:06:18.019+0000] {logging_mixin.py:190} INFO - Marked record demo-scheduled-from-ui-worldlinkfbed7fae-181a-4195-85cb-045bcee6c18d as switch_off.
[2025-01-27T10:06:18.019+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-27T10:06:18.025+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T10:06:18.025+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9843500346_2025-01-27T10-05-11-797136Z, task_id=find_reason_for_unanswered, run_id=scheduled__2025-01-27T10:05:11.797136+00:00, execution_date=20250127T100511, start_date=20250127T100617, end_date=20250127T100618
[2025-01-27T10:06:18.045+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-27T10:06:18.053+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T10:06:18.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
