[2024-12-22T04:23:32.371+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-22T04:23:32.382+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9858020419_2024-12-22T04-21-02-017377Z.find_reason_for_unanswered scheduled__2024-12-22T04:21:02.017377+00:00 [queued]>
[2024-12-22T04:23:32.387+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9858020419_2024-12-22T04-21-02-017377Z.find_reason_for_unanswered scheduled__2024-12-22T04:21:02.017377+00:00 [queued]>
[2024-12-22T04:23:32.387+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-22T04:23:32.392+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): find_reason_for_unanswered> on 2024-12-22 04:21:02.017377+00:00
[2024-12-22T04:23:32.398+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=72304) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-22T04:23:32.399+0000] {standard_task_runner.py:72} INFO - Started process 72307 to run task
[2024-12-22T04:23:32.399+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9858020419_2024-12-22T04-21-02-017377Z', 'find_reason_for_unanswered', 'scheduled__2024-12-22T04:21:02.017377+00:00', '--job-id', '786', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpj1mtcklj']
[2024-12-22T04:23:32.399+0000] {standard_task_runner.py:105} INFO - Job 786: Subtask find_reason_for_unanswered
[2024-12-22T04:23:32.424+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9858020419_2024-12-22T04-21-02-017377Z.find_reason_for_unanswered scheduled__2024-12-22T04:21:02.017377+00:00 [running]> on host 1868de310944
[2024-12-22T04:23:32.461+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9858020419_2024-12-22T04-21-02-017377Z' AIRFLOW_CTX_TASK_ID='find_reason_for_unanswered' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T04:21:02.017377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-22T04:21:02.017377+00:00'
[2024-12-22T04:23:32.462+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-22T04:23:32.463+0000] {logging_mixin.py:190} INFO - demo-scheduled-from-ui-global10f23bd5-0558-4e71-a2e3-82c2be0f9f27
[2024-12-22T04:23:32.463+0000] {logging_mixin.py:190} INFO - cause_txt: full_ring
[2024-12-22T04:23:32.467+0000] {base.py:84} INFO - Retrieving connection 'aicallagent'
[2024-12-22T04:23:32.472+0000] {sql.py:544} INFO - Running statement: UPDATE user_details SET status = 'full_ring', modified_on_utc = now() at time zone 'utc' WHERE caller_id = 'demo-scheduled-from-ui-global10f23bd5-0558-4e71-a2e3-82c2be0f9f27', parameters: None
[2024-12-22T04:23:32.474+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-22T04:23:32.475+0000] {logging_mixin.py:190} INFO - Marked record demo-scheduled-from-ui-global10f23bd5-0558-4e71-a2e3-82c2be0f9f27 as full_ring.
[2024-12-22T04:23:32.475+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-22T04:23:32.480+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-22T04:23:32.480+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9858020419_2024-12-22T04-21-02-017377Z, task_id=find_reason_for_unanswered, run_id=scheduled__2024-12-22T04:21:02.017377+00:00, execution_date=20241222T042102, start_date=20241222T042332, end_date=20241222T042332
[2024-12-22T04:23:32.491+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-22T04:23:32.501+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-22T04:23:32.502+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
