[2024-12-10T03:55:03.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T03:55:03.430+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mydag.branch_on_call_status manual__2024-12-10T03:54:59.945498+00:00 [queued]>
[2024-12-10T03:55:03.433+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mydag.branch_on_call_status manual__2024-12-10T03:54:59.945498+00:00 [queued]>
[2024-12-10T03:55:03.433+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-10T03:55:03.438+0000] {taskinstance.py:2889} INFO - Executing <Task(_BranchPythonDecoratedOperator): branch_on_call_status> on 2024-12-10 03:54:59.945498+00:00
[2024-12-10T03:55:03.443+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13924) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-10T03:55:03.444+0000] {standard_task_runner.py:72} INFO - Started process 13925 to run task
[2024-12-10T03:55:03.444+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mydag', 'branch_on_call_status', 'manual__2024-12-10T03:54:59.945498+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/testdag.py', '--cfg-path', '/tmp/tmpyfclgb_o']
[2024-12-10T03:55:03.445+0000] {standard_task_runner.py:105} INFO - Job 258: Subtask branch_on_call_status
[2024-12-10T03:55:03.465+0000] {task_command.py:467} INFO - Running <TaskInstance: mydag.branch_on_call_status manual__2024-12-10T03:54:59.945498+00:00 [running]> on host e4d9da3426d6
[2024-12-10T03:55:03.508+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mydag' AIRFLOW_CTX_TASK_ID='branch_on_call_status' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T03:54:59.945498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T03:54:59.945498+00:00'
[2024-12-10T03:55:03.508+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T03:55:03.509+0000] {python.py:240} INFO - Done. Returned value was: find_reason_for_unanswered
[2024-12-10T03:55:03.510+0000] {branch.py:38} INFO - Branch into find_reason_for_unanswered
[2024-12-10T03:55:03.510+0000] {skipmixin.py:230} INFO - Following branch ('find_reason_for_unanswered',)
[2024-12-10T03:55:03.515+0000] {skipmixin.py:278} INFO - Skipping tasks [('find_if_proper_interaction_is_completed', -1)]
[2024-12-10T03:55:03.530+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T03:55:03.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mydag, task_id=branch_on_call_status, run_id=manual__2024-12-10T03:54:59.945498+00:00, execution_date=20241210T035459, start_date=20241210T035503, end_date=20241210T035503
[2024-12-10T03:55:03.577+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-10T03:55:03.592+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-10T03:55:03.593+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
