[2025-01-08T07:47:44.903+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T07:47:44.912+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9863800249_2025-01-08T07-46-20-430627Z.find_reason_for_unanswered scheduled__2025-01-08T07:46:20.430627+00:00 [queued]>
[2025-01-08T07:47:44.916+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9863800249_2025-01-08T07-46-20-430627Z.find_reason_for_unanswered scheduled__2025-01-08T07:46:20.430627+00:00 [queued]>
[2025-01-08T07:47:44.916+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-08T07:47:44.921+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): find_reason_for_unanswered> on 2025-01-08 07:46:20.430627+00:00
[2025-01-08T07:47:44.926+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7783) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-08T07:47:44.926+0000] {standard_task_runner.py:72} INFO - Started process 7784 to run task
[2025-01-08T07:47:44.927+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9863800249_2025-01-08T07-46-20-430627Z', 'find_reason_for_unanswered', 'scheduled__2025-01-08T07:46:20.430627+00:00', '--job-id', '1005', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmposhfoutz']
[2025-01-08T07:47:44.927+0000] {standard_task_runner.py:105} INFO - Job 1005: Subtask find_reason_for_unanswered
[2025-01-08T07:47:44.947+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9863800249_2025-01-08T07-46-20-430627Z.find_reason_for_unanswered scheduled__2025-01-08T07:46:20.430627+00:00 [running]> on host 680cb867086b
[2025-01-08T07:47:44.979+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9863800249_2025-01-08T07-46-20-430627Z' AIRFLOW_CTX_TASK_ID='find_reason_for_unanswered' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T07:46:20.430627+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T07:46:20.430627+00:00'
[2025-01-08T07:47:44.980+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T07:47:44.981+0000] {logging_mixin.py:190} INFO - demo-scheduled-from-ui-global3aa65fb9-8a02-4dc5-af45-692e50f04553
[2025-01-08T07:47:44.981+0000] {logging_mixin.py:190} INFO - cause_txt: switch_off
[2025-01-08T07:47:44.984+0000] {base.py:84} INFO - Retrieving connection 'aicallagent'
[2025-01-08T07:47:44.988+0000] {sql.py:544} INFO - Running statement: UPDATE user_details SET status = 'switch_off', modified_on_utc = now() at time zone 'utc' WHERE caller_id = 'demo-scheduled-from-ui-global3aa65fb9-8a02-4dc5-af45-692e50f04553', parameters: None
[2025-01-08T07:47:44.990+0000] {sql.py:553} INFO - Rows affected: 1
[2025-01-08T07:47:44.990+0000] {logging_mixin.py:190} INFO - Marked record demo-scheduled-from-ui-global3aa65fb9-8a02-4dc5-af45-692e50f04553 as switch_off.
[2025-01-08T07:47:44.991+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-08T07:47:44.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T07:47:44.995+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9863800249_2025-01-08T07-46-20-430627Z, task_id=find_reason_for_unanswered, run_id=scheduled__2025-01-08T07:46:20.430627+00:00, execution_date=20250108T074620, start_date=20250108T074744, end_date=20250108T074744
[2025-01-08T07:47:45.020+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-08T07:47:45.029+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T07:47:45.029+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
