[2025-01-21T05:31:19.235+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-21T05:31:19.243+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9868205040_2025-01-21T05-31-00-501281Z.make_api_call scheduled__2025-01-21T05:31:00.501281+00:00 [queued]>
[2025-01-21T05:31:19.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9868205040_2025-01-21T05-31-00-501281Z.make_api_call scheduled__2025-01-21T05:31:00.501281+00:00 [queued]>
[2025-01-21T05:31:19.246+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-21T05:31:19.251+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): make_api_call> on 2025-01-21 05:31:00.501281+00:00
[2025-01-21T05:31:19.255+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-21T05:31:19.256+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2025-01-21T05:31:19.256+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9868205040_2025-01-21T05-31-00-501281Z', 'make_api_call', 'scheduled__2025-01-21T05:31:00.501281+00:00', '--job-id', '1112', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmphxsihimh']
[2025-01-21T05:31:19.257+0000] {standard_task_runner.py:105} INFO - Job 1112: Subtask make_api_call
[2025-01-21T05:31:19.276+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9868205040_2025-01-21T05-31-00-501281Z.make_api_call scheduled__2025-01-21T05:31:00.501281+00:00 [running]> on host 680cb867086b
[2025-01-21T05:31:19.310+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9868205040_2025-01-21T05-31-00-501281Z' AIRFLOW_CTX_TASK_ID='make_api_call' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T05:31:00.501281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T05:31:00.501281+00:00'
[2025-01-21T05:31:19.310+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-21T05:31:22.392+0000] {logging_mixin.py:190} INFO - API call to http://192.168.79.109:8001/call completed with status code 500
channelId: demo-scheduled-from-ui-global8dd6328a-3270-4d37-8900-9fe6e84a628e
[2025-01-21T05:31:22.392+0000] {python.py:240} INFO - Done. Returned value was: 500
[2025-01-21T05:31:22.404+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-21T05:31:22.404+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9868205040_2025-01-21T05-31-00-501281Z, task_id=make_api_call, run_id=scheduled__2025-01-21T05:31:00.501281+00:00, execution_date=20250121T053100, start_date=20250121T053119, end_date=20250121T053122
[2025-01-21T05:31:22.434+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-21T05:31:22.447+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-21T05:31:22.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
