[2025-01-21T05:35:23.444+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-21T05:35:23.452+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9868205040_2025-01-21T05-34-53-588710Z.wait_until_call scheduled__2025-01-21T05:34:53.588710+00:00 [queued]>
[2025-01-21T05:35:23.455+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9868205040_2025-01-21T05-34-53-588710Z.wait_until_call scheduled__2025-01-21T05:34:53.588710+00:00 [queued]>
[2025-01-21T05:35:23.456+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-21T05:35:23.461+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): wait_until_call> on 2025-01-21 05:34:53.588710+00:00
[2025-01-21T05:35:23.465+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-21T05:35:23.466+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2025-01-21T05:35:23.466+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9868205040_2025-01-21T05-34-53-588710Z', 'wait_until_call', 'scheduled__2025-01-21T05:34:53.588710+00:00', '--job-id', '1120', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpnt4u7_hm']
[2025-01-21T05:35:23.467+0000] {standard_task_runner.py:105} INFO - Job 1120: Subtask wait_until_call
[2025-01-21T05:35:23.489+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9868205040_2025-01-21T05-34-53-588710Z.wait_until_call scheduled__2025-01-21T05:34:53.588710+00:00 [running]> on host 680cb867086b
[2025-01-21T05:35:23.522+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9868205040_2025-01-21T05-34-53-588710Z' AIRFLOW_CTX_TASK_ID='wait_until_call' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T05:34:53.588710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T05:34:53.588710+00:00'
[2025-01-21T05:35:23.523+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-21T05:35:23.524+0000] {logging_mixin.py:190} INFO - 243
[2025-01-21T05:36:23.524+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-21T05:36:23.530+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-21T05:36:23.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9868205040_2025-01-21T05-34-53-588710Z, task_id=wait_until_call, run_id=scheduled__2025-01-21T05:34:53.588710+00:00, execution_date=20250121T053453, start_date=20250121T053523, end_date=20250121T053623
[2025-01-21T05:36:23.581+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-21T05:36:23.592+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-21T05:36:23.593+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
