[2025-01-22T09:06:05.262+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T09:06:05.269+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9868205040_2025-01-22T09-05-52-333234Z.wait_until_call scheduled__2025-01-22T09:05:52.333234+00:00 [queued]>
[2025-01-22T09:06:05.272+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9868205040_2025-01-22T09-05-52-333234Z.wait_until_call scheduled__2025-01-22T09:05:52.333234+00:00 [queued]>
[2025-01-22T09:06:05.272+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-22T09:06:05.277+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): wait_until_call> on 2025-01-22 09:05:52.333234+00:00
[2025-01-22T09:06:05.282+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=22495) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T09:06:05.283+0000] {standard_task_runner.py:72} INFO - Started process 22496 to run task
[2025-01-22T09:06:05.283+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9868205040_2025-01-22T09-05-52-333234Z', 'wait_until_call', 'scheduled__2025-01-22T09:05:52.333234+00:00', '--job-id', '1178', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpo463z137']
[2025-01-22T09:06:05.284+0000] {standard_task_runner.py:105} INFO - Job 1178: Subtask wait_until_call
[2025-01-22T09:06:05.304+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9868205040_2025-01-22T09-05-52-333234Z.wait_until_call scheduled__2025-01-22T09:05:52.333234+00:00 [running]> on host 680cb867086b
[2025-01-22T09:06:05.337+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9868205040_2025-01-22T09-05-52-333234Z' AIRFLOW_CTX_TASK_ID='wait_until_call' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T09:05:52.333234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T09:05:52.333234+00:00'
[2025-01-22T09:06:05.337+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T09:06:05.338+0000] {logging_mixin.py:190} INFO - 254
[2025-01-22T09:07:05.339+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-22T09:07:05.345+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T09:07:05.346+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9868205040_2025-01-22T09-05-52-333234Z, task_id=wait_until_call, run_id=scheduled__2025-01-22T09:05:52.333234+00:00, execution_date=20250122T090552, start_date=20250122T090605, end_date=20250122T090705
[2025-01-22T09:07:05.387+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T09:07:05.398+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T09:07:05.399+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
