[2025-01-27T04:51:25.714+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T04:51:25.722+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: call_9868205040_2025-01-27T04-51-08-963563Z.wait_until_call scheduled__2025-01-27T04:51:08.963563+00:00 [queued]>
[2025-01-27T04:51:25.725+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: call_9868205040_2025-01-27T04-51-08-963563Z.wait_until_call scheduled__2025-01-27T04:51:08.963563+00:00 [queued]>
[2025-01-27T04:51:25.725+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-27T04:51:25.730+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): wait_until_call> on 2025-01-27 04:51:08.963563+00:00
[2025-01-27T04:51:25.734+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-27T04:51:25.735+0000] {standard_task_runner.py:72} INFO - Started process 320 to run task
[2025-01-27T04:51:25.736+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'call_9868205040_2025-01-27T04-51-08-963563Z', 'wait_until_call', 'scheduled__2025-01-27T04:51:08.963563+00:00', '--job-id', '1257', '--raw', '--subdir', 'DAGS_FOLDER/complete_dag.py', '--cfg-path', '/tmp/tmpu7hbvae4']
[2025-01-27T04:51:25.736+0000] {standard_task_runner.py:105} INFO - Job 1257: Subtask wait_until_call
[2025-01-27T04:51:25.756+0000] {task_command.py:467} INFO - Running <TaskInstance: call_9868205040_2025-01-27T04-51-08-963563Z.wait_until_call scheduled__2025-01-27T04:51:08.963563+00:00 [running]> on host 680cb867086b
[2025-01-27T04:51:25.788+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='call_9868205040_2025-01-27T04-51-08-963563Z' AIRFLOW_CTX_TASK_ID='wait_until_call' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T04:51:08.963563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T04:51:08.963563+00:00'
[2025-01-27T04:51:25.788+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T04:51:25.789+0000] {logging_mixin.py:190} INFO - 269
[2025-01-27T04:52:25.789+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-27T04:52:25.796+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T04:52:25.796+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=call_9868205040_2025-01-27T04-51-08-963563Z, task_id=wait_until_call, run_id=scheduled__2025-01-27T04:51:08.963563+00:00, execution_date=20250127T045108, start_date=20250127T045125, end_date=20250127T045225
[2025-01-27T04:52:25.821+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-27T04:52:25.833+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-27T04:52:25.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
